openapi: 3.0.1
info:
    title: CinemaCity User API
    version: 1.0.0
paths: 
    /user/register:
        post:
            summary: Register a new user
            requestBody:
                required: true
                content: 
                    application/json:
                        schema:
                            $ref: '#components/schemas/RegisterUserRequest'
            responses: 
                '200':
                    description: Success
    /user/login:
        post:
            summary: Login user
            requestBody: 
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#components/schemas/LoginRequest'
            responses:
                '200':
                    description: Success
components:
    schemas:
        RegisterUserRequest:
            type: object
            properties: 
                email:
                    type: string
                password:
                    type: string
        LoginRequest:
            type: object
            properties:
                email:
                    type: string
                password:
                    type: string

                


